name: "\U0001F41E Bug report"
description: Report an issue with Reanimated
labels: "needs-review"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Before you proceed:

        - Make sure to look for similar issues in the React Native Reanimated repository
        - Make sure to add `'react-native-reanimated/plugin'` to your `babel.config.js`
        - Make sure to clean cache in your project. Depending on your setup this could be done by:
          - `yarn start --reset-cache` or
          - `npm start -- --reset-cache` or
          - `expo start -c`

        Please provide all the information requested.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of what the bug is. Include screenshots or a video if needed. Tell us what were you expecting to happen instead of what is happening now. 
    validations:
      required: true


  - type: input
    id: repro
    attributes:
      label: Snack or a link to a repository
      description: |
        Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub under your username that reproduces the issue.
        Here are some tips for providing a minimal example: [https://stackoverflow.com/help/mcve](https://stackoverflow.com/help/mcve).
      placeholder: Link to a Snack or a GitHub repository
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: Platforms
      description: On what platform your application is running on?
      multiple: true
      options:
        - Android
        - iOS
        - Web
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: Runtime
      description: What runtime is your application using?
      options:
        - JSC
        - Hermes

  - type: dropdown
    id: workflow
    attributes:
      label: Workflow
      description: How your application is managed? Not sure? Read [this part of Expo documentation](https://docs.expo.dev/introduction/managed-vs-bare/)
      options:
        - React Native (without Expo)
        - Expo bare workflow
        - Expo managed workflow

  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      description: What architecture your application is running on? If you're not sure then it's probably Paper.
      options:
        - Paper (current)
        - Fabric (new)

  - type: dropdown
    id: build-type
    attributes:
      label: Build type
      description: What mode your application is running? During the development it's probably debug mode.
      options:
        - debug mode
        - release mode

  - type: dropdown
    id: emulator
    attributes:
      label: Device
      description: How are you running your application?
      options:
        - iOS simulator
        - Android emulator
        - real device

  - type: input
    id: device-model
    attributes:
      label: Real device model
      placeholder: ex. Samsung A22
