name: "\U0001F41E Bug report"
description: Report an issue with Reanimated
labels: "needs-review"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Before you proceed:

        - Make sure to look for similar issues in the React Native Reanimated repository
        - Make sure to add `'react-native-reanimated/plugin'` to your `babel.config.js`
        - Make sure to clean cache in your project. Depending on your setup:
          - `yarn start --reset-cache` or
          - `npm start -- --reset-cache` or
          - `expo start -c`

        Please provide all the information requested.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of what the bug is. Include screenshots or a video if needed. Tell us what were you expecting to happen when this occured. 
    validations:
      required: true


  - type: textarea
    id: repro
    attributes:
      label: Snack or a link to a repository
      description: |
        Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub under your username.
        Here are some tips for providing a minimal example: [https://stackoverflow.com/help/mcve](https://stackoverflow.com/help/mcve).
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: Platforms
      description: On what system your application is running on?
      multiple: true
      options:
        - Android
        - iOS
        - Web
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: Runtime
      description: What runtime your application is running on?
      options:
        - JSC
        - Hermes

  - type: dropdown
    id: workflow
    attributes:
      label: Workflow
      options:
        - React Native (without Expo)
        - Expo Bare Workflow
        - Expo Managed

  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      options:
        - Paper (current)
        - Fabric (new)

  - type: dropdown
    id: build-type
    attributes:
      label: Build type
      options:
        - debug mode
        - release mode

  - type: dropdown
    id: emulator
    attributes:
      label: Device
      description: How are you running your app?
      options:
        - iOS simulator
        - Android emulator
        - real device

  - type: input
    id: device-model
    attributes:
      label: Real device model
      placeholder: ex. Samsung A22
