name: Check issue template
on:
  issues:
    types: [opened, edited]

jobs:
  main:
    if: ${{ !contains(github.event.issue.labels.*.name, 'maintainer-issue') }}
    runs-on: ubuntu-latest
    concurrency:
      group: needs-more-info-${{ github.event.issue.number }}
      cancel-in-progress: true
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'software-mansion-labs/swmansion-bot'
          ref: main

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Actions
        run: yarn install

      - name: Needs More Info
        uses: ./needs-more-info
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          needs-more-info-label: needs-more-info
          required-sections: 'Description;Steps to reproduce;Snack or a link to a repository;Reanimated version;React Native version;Platforms'
          needs-more-info-response: "Hey! 👋 \n\nIt looks like you've omitted a few important sections from the issue template."